// Server Base URLs
@baseUrl = https://fhirdemo5.azurewebsites.net
@baseUrlFirely = https://server.fire.ly/r4

// set a resource name
@resourceName = Patient

// use an ID valid for that resource type on that server
@compartmentId = 75014c51-5256-489a-ad1e-284740045d5a
@compartmentIdFirely = a9332dce-4484-4f7c-a9bb-4e6e72d68045


### Root Server Search - GET
@name = RootServerGet

GET {{baseUrl}}
Accept: application/fhir+json

### Root Server Search - POST

@name = RootServerPost
POST {{baseUrl}}/_search
Accept: application/fhir+json
Content-Type: application/x-www-form-urlencoded

### Resource Search - GET
@name = ResourceGet
GET {{baseUrl}}/{{resourceName}}
Accept: application/fhir+json

### Resource Search - POST

@name = ResourcePost
POST {{baseUrl}}/{{resourceName}}/_search
Accept: application/fhir+json
Content-Type: application/x-www-form-urlencoded


### Compartment Search - GET
@name = CompartmentGet
GET {{baseUrlFirely}}/{{resourceName}}/{{compartmentIdFirely}}
Accept: application/fhir+json

### Compartment Search - POST

@name = CompartmentPost
POST {{baseUrlFirely}}/{{resourceName}}/{{compartmentIdFirely}}/_search
Accept: application/fhir+json
Content-Type: application/x-www-form-urlencoded


