// Server Base URLs
@baseUrl = https://fhirdemo5.azurewebsites.net

// set a resource name
@resourceName = Patient

// use an ID valid for that resource type on that server
@patientId = 75014c51-5256-489a-ad1e-284740045d5a

### 01-Root Server Search - GET 
@name = RootServerGet
GET {{baseUrl}}
Accept: application/fhir+json

### 02-Root Server Search - POST
@name = RootServerPost
POST {{baseUrl}}/_search
Accept: application/fhir+json
Content-Type: application/x-www-form-urlencoded


### 03-Resource Search - GET
@name = ResourceGet
GET {{baseUrl}}/{{resourceName}}
Accept: application/fhir+json

### 04-Resource Search - POST
@name = ResourcePost
POST {{baseUrl}}/{{resourceName}}/_search
Accept: application/fhir+json
Content-Type: application/x-www-form-urlencoded


### 05-Compartment Search - GET
@name = CompartmentGet
GET {{baseUrl}}/{{resourceName}}/{{patientId}}/Encounter
Accept: application/fhir+json

### 06-Compartment Search - POST
@name = CompartmentPost
POST {{baseUrl}}/{{resourceName}}/{{patientId}}/Encounter/_search
Accept: application/fhir+json
Content-Type: application/x-www-form-urlencoded
