// Base URLs
@baseUrl = https://fhirdemo5.azurewebsites.net


### Missing - patients without a family name
GET {{baseUrl}}/Patient?family:missing=true
Accept: application/fhir+json

// looking at family name of Abernathy524

### Default Text handling: starts with or equals, case-insensitive
GET {{baseUrl}}/Patient?family=Abernathy
Accept: application/fhir+json

### Default Text handling: starts with or equals, case-insensitive
GET {{baseUrl}}/Patient?family=524
Accept: application/fhir+json


### Contains: contains or equals, case-insensitive
GET {{baseUrl}}/Patient?family:contains=524
Accept: application/fhir+json

### Exact: exact match text, case-sensitive
GET {{baseUrl}}/Patient?family:exact=abernathy524
Accept: application/fhir+json

### Exact: exact match text, case-sensitive
GET {{baseUrl}}/Patient?family:exact=Abernathy524
Accept: application/fhir+json

### Text: advanced text searching (e.g., regex, lucene, etc.)
