// Base URLs
@baseUrl = https://fhirdemo5.azurewebsites.net


### Default Date handling: defaults to equality
GET {{baseUrl}}/Patient?birthdate=1998-01-27
Accept: application/fhir+json

### Explicit Equality Test: eq
GET {{baseUrl}}/Patient?birthdate=eq1998-01-27
Accept: application/fhir+json

### Not-equal: ne
GET {{baseUrl}}/Patient?birthdate=ne1998-01-27
Accept: application/fhir+json

### Greater Than: gt
GET {{baseUrl}}/Patient?birthdate=gt1998-01-27
Accept: application/fhir+json

### Greater Than or Equal To: ge (more results)
GET {{baseUrl}}/Patient?birthdate=ge1998-01-27
Accept: application/fhir+json

### Less Than: lt
GET {{baseUrl}}/Patient?birthdate=lt1998-01-27
Accept: application/fhir+json

### Less Than or Equal To: le (more results)
GET {{baseUrl}}/Patient?birthdate=le1998-01-27
Accept: application/fhir+json

// ...
