// Base URLs
@baseUrl = https://fhirdemo5.azurewebsites.net


// Family: Abernathy524, Given: Adrienne302

### AND search: Join two different parameters
GET {{baseUrl}}/Patient?family=abernathy&given=Adrienne302
Accept: application/fhir+json

### AND search: Join two different parameters, with modifiers
GET {{baseUrl}}/Patient?family=abernathy&given:contains=302
Accept: application/fhir+json

### OR search: Join two values 
GET {{baseUrl}}/Patient?family=brito,Abernathy524
Accept: application/fhir+json

### OR search: Join two values, with modifiers
GET {{baseUrl}}/Patient?family:exact=brito,Abernathy524
Accept: application/fhir+json

### Special Case: Composite Search on Name (family portion)
GET {{baseUrl}}/Patient?name=Abernathy524
Accept: application/fhir+json

### Special Case: Composite Search on Name (given portion)
GET {{baseUrl}}/Patient?name=Adrienne302
Accept: application/fhir+json

### Special Case: Composite Search on Name with OR values
GET {{baseUrl}}/Patient?name=Brito172,Adrienne302
Accept: application/fhir+json

### Special Case: Composite Search on Name with OR values and Modifiers
GET {{baseUrl}}/Patient?name:contains=302,172
Accept: application/fhir+json

