// Base URLs
@baseUrlTFO = http://test.fhir.org/r4
@baseUrlHapi = http://hapi.fhir.org/baseR4
@baseUrlFirely = https://server.fire.ly/r4
@baseUrlArgo = http://server.subscriptions.argo.run/r4

@patientIdArgo = CBZ8032
@patientIdFirely = b426b062-8273-4b93-a907-de3176c0567d



### Search for Encounters with a subject
GET {{baseUrlArgo}}/Encounter?subject={{patientIdArgo}}
Accept: application/fhir+json

### Search for Encounters with a patient (different parameter)
GET {{baseUrlArgo}}/Encounter?patient={{patientIdArgo}}
Accept: application/fhir+json

### Search for Encounters with a subject that is a Patient resource
GET {{baseUrlArgo}}/Encounter?subject:Patient={{patientIdArgo}}
Accept: application/fhir+json



### Root Search with a common parameter
# Encounter and Observation both have a `patient` search parameter
# Patient does not, so is not returned
GET {{baseUrlFirely}}/?patient={{patientIdFirely}}&_type=Patient,Encounter,Observation
Accept: application/fhir+json
