// Base URLs
@baseUrl = https://fhirdemo5.azurewebsites.net

@patientId = 75014c51-5256-489a-ad1e-284740045d5a


### Search for Encounters with a subject
GET {{baseUrl}}/Encounter?subject={{patientId}}
Accept: application/fhir+json

### Search for Encounters with a patient (different parameter)
GET {{baseUrl}}/Encounter?patient={{patientId}}
Accept: application/fhir+json

### Search for Encounters with a subject that is a Patient resource
GET {{baseUrl}}/Encounter?subject:Patient={{patientId}}
Accept: application/fhir+json


### Root Search with a common parameter
# Encounter and Observation both have a `patient` search parameter
# Patient does not, so is not returned
GET {{baseUrl}}/?patient={{patientId}}&_type=Patient,Encounter,Observation
Accept: application/fhir+json
